// ui-store
export const IS_SHOW_FILTER = 'IS_SHOW_FILTER'
export const IS_SHOW_SOCIAL = 'IS_SHOW_SOCIAL'
export const IS_SHOW_FOLLOW = 'IS_SHOW_FOLLOW'
export const IS_NOTIFY_BOX_OPEN = 'IS_NOTIFY_BOX_OPEN'
export const IS_SHOW_FORGET_PWD = 'IS_SHOW_FORGET_PWD'
export const IS_LEFT_MENU_OPEN = 'IS_LEFT_MENU_OPEN'
export const FOLLOW_TRADER_ID = 'FOLLOW_TRADER_ID'
export const TRADER_NUM = "TRADER_NUM"
export const TRADER_NICKNAME ='TRADER_NICKNAME'
export const TRADER_NICKNAME_WITH_NUM = 'TRADER_NICKNAME_WITH_NUM'

export const ACTION_IS_SHOW_FILTER = 'ACTION_IS_SHOW_FILTER'
export const ACTION_IS_SHOW_SOCIAL = 'ACTION_IS_SHOW_SOCIAL'
export const ACTION_IS_SHOW_FOLLOW = 'ACTION_IS_SHOW_FOLLOW'
export const ACTION_IS_NOTIFY_BOX_OPEN = 'ACTION_IS_NOTIFY_BOX_OPEN'
export const ACTION_IS_SHOW_FORGET_PWD = 'ACTION_IS_SHOW_FORGET_PWD'
export const ACTION_IS_LEFT_MENU_OPEN = 'ACTION_IS_LEFT_MENU_OPEN'
export const ACTION_FOLLOW_TRADER_ID = 'ACTION_FOLLOW_TRADER_ID'
export const ACTION_TRADER_NUM = 'ACTION_TRADER_NUM'
export const ACTION_TRADER_NICKNAME = 'ACTION_TRADER_NICKNAME'
export const ACTION_TRADER_NICKNAME_WITH_NUM = 'ACTION_TRADER_NICKNAME_WITH_NUM'
export const ACTION_FILTER_COMPONENT = 'ACTION_FILTER_COMPONENT'

// auth-store
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// member-store
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_ERROR = 'USER_ERROR'
export const CURRENT_ACCT = 'CURRENT_ACCT'

export const ACTION_UPDATE_CURRENT_ACCT = 'ACTION_UPDATE_CURRENT_ACCT'
